#!/usr/bin/env python3
"""
Multi-Island AlphaEvolve on Transaction Scheduling Problem.

Each island has its own independent CVT-MAP-Elites archive. Islands are seeded
from diverse solutions generated by a heavy thinking model. Migration occurs
every 200 evaluations in a circular pattern (island i -> i+1, last -> first),
transferring the top 10% of solutions.
"""

import asyncio
import sys
import time
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

# Add algoforge to path (must be before algoforge imports)
ALGOFORGE_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ALGOFORGE_ROOT))

from algoforge.utils import ResilientProcessPool

# Add txn_scheduling resources to path
TXN_RESOURCES = ALGOFORGE_ROOT.parent / "ADRS-Leaderboard" / "problems" / "txn_scheduling" / "resources"
sys.path.insert(0, str(TXN_RESOURCES))

from algoforge.core import Program, EvaluationResult
from algoforge.pool import CVTMAPElitesPool
from algoforge.llm import PromptBuilder, ProgramWithScore, OutputMode
from algoforge.behavior.extractor import FeatureVector
import ast
import re
import json
import numpy as np

# Import shared components from run.py
from run import (
    TxnSchedulingBehaviorExtractor,
    validate_python_syntax,
    quick_validate_code,
    extract_and_validate_code,
    evaluate_code_in_process,
    _init_workloads,
    save_state,
    format_metrics_for_llm,
    generate_meta_advice,
)

# These will be set in main() after _init_workloads()
WORKLOADS = None
BASELINE = None
EFFECTIVE_OPTIMAL = None


def compute_score(makespan: float) -> float:
    """Compute 0-100 raw score using leaderboard formula."""
    if makespan >= BASELINE:
        return 0.0
    if makespan <= EFFECTIVE_OPTIMAL:
        return 100.0
    return ((BASELINE - makespan) / (BASELINE - EFFECTIVE_OPTIMAL)) * 100


def score_fn(output: dict) -> float:
    """Score using leaderboard formula."""
    if output is None or "error" in output:
        return 0.0
    return compute_score(output.get("makespan", BASELINE))

from txn_simulator import Workload
from workloads import WORKLOAD_1, WORKLOAD_2, WORKLOAD_3
from prompts import PROBLEM_DESCRIPTION, FUNCTION_SIGNATURE, SEED_PROGRAM, DIVERSITY_SEED_PROMPT, META_ADVISOR_PROMPT
import litellm
import logging

# Suppress LiteLLM debug spam
logging.getLogger("LiteLLM").setLevel(logging.ERROR)
logging.getLogger("litellm").setLevel(logging.ERROR)
logging.getLogger("httpx").setLevel(logging.WARNING)
litellm.suppress_debug_info = True
litellm.set_verbose = False

# Register custom models
litellm.register_model({
    "openrouter/google/gemini-2.5-flash-lite": {
        "max_tokens": 32768,
        "max_input_tokens": 1048576,
        "max_output_tokens": 32768,
        "input_cost_per_token": 0.0000001,
        "output_cost_per_token": 0.0000004,
        "litellm_provider": "openrouter",
    },
    "openrouter/deepseek/deepseek-v3.2": {
        "max_tokens": 163840,
        "max_input_tokens": 163840,
        "max_output_tokens": 163840,
        "input_cost_per_token": 0.00000026,
        "output_cost_per_token": 0.00000038,
        "litellm_provider": "openrouter",
    },
    "openrouter/qwen/qwen3-coder-30b-a3b-instruct": {
        "max_tokens": 32768,
        "max_input_tokens": 160000,
        "max_output_tokens": 32768,
        "input_cost_per_token": 0.00000007,
        "output_cost_per_token": 0.00000027,
        "litellm_provider": "openrouter",
    },
    "openrouter/z-ai/glm-4.7": {
        "max_tokens": 32768,
        "max_input_tokens": 202752,
        "max_output_tokens": 32768,
        "input_cost_per_token": 0.0000004,
        "output_cost_per_token": 0.0000015,
        "litellm_provider": "openrouter",
    },
})


@dataclass
class Island:
    """An island with its own CVT-MAP-Elites archive."""

    index: int
    pool: CVTMAPElitesPool
    best_score: float = 0.0
    best_program: Optional[Program] = None
    eval_count: int = 0
    acceptance_count: int = 0

    def get_top_elites(self, fraction: float = 0.1) -> list[tuple[Program, EvaluationResult, FeatureVector]]:
        """Get top fraction of elites by score."""
        elites = list(self.pool._elites.values())
        if not elites:
            return []
        elites.sort(key=lambda e: e.result.primary_score, reverse=True)
        n_top = max(1, int(len(elites) * fraction))
        return [(e.program, e.result, e.behavior) for e in elites[:n_top]]

    def receive_migrants(self, migrants: list[tuple[Program, EvaluationResult]]) -> int:
        """Receive migrants from another island. Returns count of accepted."""
        accepted = 0
        for program, result in migrants:
            if self.pool.add(program, result):
                accepted += 1
                if result.primary_score > self.best_score:
                    self.best_score = result.primary_score
                    self.best_program = program
        return accepted


# State tracking
STATE_FILE = Path(__file__).parent / "evolution_state_multi_island.json"

# Budget
BUDGET_USD = 3.0


def save_multi_island_state(
    generation: int,
    islands: list[Island],
    global_best_score: float,
    global_best_program: Program,
    total_cost: float,
    extra_info: dict = None,
    filename: Path = None,
):
    """Save multi-island evolution state to JSON file."""
    island_data = []
    for island in islands:
        elites = []
        try:
            for cell_idx, elite in island.pool._elites.items():
                elite_info = {
                    "cell_index": int(cell_idx),
                    "score": float(elite.result.primary_score),
                    "code": elite.program.code,
                }
                elites.append(elite_info)
        except AttributeError:
            pass
        elites.sort(key=lambda x: x["score"], reverse=True)

        island_data.append({
            "index": island.index,
            "archive_size": island.pool.size(),
            "best_score": float(island.best_score),
            "eval_count": island.eval_count,
            "acceptance_count": island.acceptance_count,
            "top_elites": elites[:5],  # Top 5 per island
        })

    state = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "generation": generation,
        "n_islands": len(islands),
        "global_best_score": float(global_best_score),
        "total_cost_usd": float(total_cost),
        "global_best_program": {
            "code": global_best_program.code,
            "metadata": {k: float(v) if isinstance(v, (int, float)) else str(v)
                        for k, v in (global_best_program.metadata or {}).items()},
        },
        "islands": island_data,
    }

    if extra_info:
        state.update(extra_info)

    target_file = filename if filename else STATE_FILE
    temp_file = target_file.with_suffix(".json.tmp")
    with open(temp_file, "w") as f:
        json.dump(state, f, indent=2)
    temp_file.rename(target_file)


async def generate_with_thinking(prompt: str, model: str, temperature: float = 0.7) -> dict:
    """Generate code using a model with thinking/reasoning enabled."""
    start = time.time()
    try:
        call_kwargs = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": temperature,
            "max_tokens": 30000,
            "timeout": 300,
        }

        # Enable reasoning for DeepSeek models
        if "deepseek" in model.lower():
            call_kwargs["reasoning"] = {"enabled": True}

        response = await litellm.acompletion(**call_kwargs)
        elapsed = time.time() - start
        content = response.choices[0].message.content
        cost = litellm.completion_cost(completion_response=response)
        tokens = response.usage.total_tokens

        return {
            "content": content,
            "cost": cost,
            "tokens": tokens,
            "elapsed": elapsed,
            "model": model,
        }
    except Exception as e:
        elapsed = time.time() - start
        return {"error": str(e), "elapsed": elapsed}


async def generate_for_island(island_idx: int, prompt: str, model: str, temperature: float) -> dict:
    """Generate code for one island asynchronously."""
    start = time.time()
    try:
        response = await litellm.acompletion(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=temperature,
            max_tokens=30000,
            timeout=300,
        )
        elapsed = time.time() - start
        content = response.choices[0].message.content
        cost = litellm.completion_cost(completion_response=response)
        tokens = response.usage.total_tokens
        print(f"  [LLM] Island {island_idx} done in {elapsed:.1f}s, {tokens} tokens")
        return {
            "island": island_idx,
            "content": content,
            "cost": cost,
            "tokens": tokens,
            "model": model,
        }
    except Exception as e:
        elapsed = time.time() - start
        print(f"  [LLM] Island {island_idx} FAILED after {elapsed:.1f}s: {e}")
        return {"island": island_idx, "error": str(e)}


def main():
    import random

    # Initialize workloads in main process
    global WORKLOADS, BASELINE, EFFECTIVE_OPTIMAL
    WORKLOADS, BASELINE, EFFECTIVE_OPTIMAL, _, _ = _init_workloads()

    # Model configuration
    LIGHT_MODELS = [
        'openrouter/qwen/qwen3-coder-30b-a3b-instruct',
        'openrouter/google/gemini-2.5-flash-lite',
        'openrouter/deepseek/deepseek-v3.2',
    ]
    # Heavy model with thinking for initial seed generation
    HEAVY_THINKING_MODEL = 'openrouter/deepseek/deepseek-v3.2'
    HEAVY_MODEL = 'openrouter/deepseek/deepseek-v3.2'

    n_workers = 8
    n_inspirations = 2
    n_islands = 3              # Fixed number of islands
    n_init_seeds = 6           # Generate this many seeds, pick best n_islands
    n_solutions_per_seed = 20  # Solutions generated per seed to form an island
    migration_intervals = [700, 1200]  # First migration at 700, then every 1200
    migration_fraction = 0.1   # Top 10% migrate

    # Evaluate seed program
    print(f"Evaluating seed program...", flush=True)

    seed_output = evaluate_code_in_process(SEED_PROGRAM)
    seed_score = score_fn(seed_output)
    seed_exec_time = seed_output.get("wall_time", 60.0)
    best_makespan = seed_output.get("makespan", BASELINE)
    print(f"  Seed: makespan={best_makespan:.0f}, score={seed_score:.1f}, time={seed_exec_time:.1f}s", flush=True)

    seed_program = Program(code=SEED_PROGRAM, metadata={
        "execution_time": seed_exec_time,
        "primary_score": seed_score,
        "workload_1_score": seed_output.get("workload_1_score", 0.0),
        "workload_2_score": seed_output.get("workload_2_score", 0.0),
        "workload_3_score": seed_output.get("workload_3_score", 0.0),
    })

    global_best_score = seed_score
    global_best_program = seed_program

    print(f"{'='*70}")
    print(f"Multi-Island AlphaEvolve - Transaction Scheduling")
    print(f"{'='*70}")
    print(f"  Baseline makespan:    {BASELINE}")
    print(f"  Effective optimal:    {EFFECTIVE_OPTIMAL:.0f}")
    print(f"  Seed makespan:        {best_makespan:.0f} (score: {seed_score:.1f})")
    print(f"  Budget:               ${BUDGET_USD:.2f}")
    print(f"  Islands:              {n_islands} (best of {n_init_seeds} seeds)")
    print(f"  Solutions per seed:   {n_solutions_per_seed}")
    print(f"  Migration intervals:  {migration_intervals[0]} first, then {migration_intervals[1]} evals")
    print(f"  Migration fraction:   {migration_fraction*100:.0f}%")
    print(f"  Heavy model (think):  {HEAVY_THINKING_MODEL}")
    print(f"  Light models:         {', '.join(LIGHT_MODELS)}")
    print(f"{'='*70}\n")

    generation = 0
    total_cost = 0.0

    executor = ResilientProcessPool(max_workers=n_workers)
    extractor = TxnSchedulingBehaviorExtractor(max_time=200.0)

    async def initialize_islands() -> list[Island]:
        """
        Initialize islands using heavy thinking model.

        Phase 1: Generate n_init_seeds diverse seeds with heavy thinking model
        Phase 2: Pick best n_islands seeds
        Phase 3: Generate n_solutions_per_seed variants for ALL seeds (for CVT diversity)
        Phase 4: Create n_islands islands, each with CVT built from random 50% of ALL programs
        """
        nonlocal total_cost, global_best_score, global_best_program

        # Phase 1: Generate diverse seeds using heavy model with thinking
        print(f"\n[Init Phase 1] Generating {n_init_seeds} diverse seeds with heavy THINKING model...", flush=True)

        # Start with original seed
        all_seeds = [(SEED_PROGRAM, seed_score, seed_output)]

        for i in range(n_init_seeds):
            # Build prompt with all existing seeds in context
            existing_seeds_text = "\n\n---\n\n".join([
                f"### Seed {j+1} (Score: {score:.1f}):\n```python\n{code}\n```"
                for j, (code, score, _) in enumerate(all_seeds)
            ])
            prompt = DIVERSITY_SEED_PROMPT.format(existing_seeds=existing_seeds_text)

            print(f"  [Seed {i+1}/{n_init_seeds}] Generating with THINKING enabled ({len(all_seeds)} seeds in context)...", flush=True)

            # Use thinking-enabled generation
            result = await generate_with_thinking(prompt, HEAVY_THINKING_MODEL, temperature=0.7)

            if "error" in result:
                print(f"  [Seed {i+1}] ERROR: {result['error'][:50]}", flush=True)
                continue

            total_cost += result["cost"]
            new_code, validation_error = extract_and_validate_code(result["content"])

            if new_code:
                try:
                    eval_result = await executor.run(evaluate_code_in_process, new_code, timeout=120)
                except (TimeoutError, RuntimeError) as e:
                    eval_result = {"error": str(e)}
                if "error" not in eval_result:
                    new_score = score_fn(eval_result)
                    all_seeds.append((new_code, new_score, eval_result))
                    print(f"  [Seed {i+1}] OK - score: {new_score:.1f}, tokens: {result['tokens']}, time: {result['elapsed']:.1f}s", flush=True)

                    if new_score > global_best_score:
                        global_best_score = new_score
                        global_best_program = Program(code=new_code, metadata={
                            "execution_time": eval_result.get("wall_time", 60.0),
                            "primary_score": new_score,
                        })
                else:
                    print(f"  [Seed {i+1}] EVAL FAIL: {eval_result['error'][:50]}", flush=True)
            else:
                print(f"  [Seed {i+1}] VALIDATION FAIL: {validation_error}", flush=True)

        print(f"[Init Phase 1] Generated {len(all_seeds)-1} new seeds (total: {len(all_seeds)})", flush=True)

        # Phase 2: Select best n_islands seeds
        all_seeds.sort(key=lambda x: x[1], reverse=True)
        selected_seeds = all_seeds[:n_islands]
        print(f"\n[Init Phase 2] Selected top {len(selected_seeds)} seeds for islands:", flush=True)
        for i, (_, score, _) in enumerate(selected_seeds):
            print(f"  Island {i}: seed score {score:.1f}", flush=True)

        # Phase 3: Generate variants for ALL seeds to build diverse CVT pool
        print(f"\n[Init Phase 3] Generating {n_solutions_per_seed} variants per seed ({len(all_seeds)} seeds)...", flush=True)

        # Collect ALL valid programs and their behaviors (for CVT initialization)
        all_valid_programs = []  # List of {"code", "score", "output", "execution_time", "seed_idx"}
        all_behavior_vectors = []

        for seed_idx, (seed_code, s_score, s_output) in enumerate(all_seeds):
            print(f"\n  [Seed {seed_idx}] Generating {n_solutions_per_seed} variants (score: {s_score:.1f})...", flush=True)

            # Add the seed itself
            all_valid_programs.append({
                "code": seed_code,
                "score": s_score,
                "output": s_output,
                "execution_time": s_output.get("wall_time", 60.0),
                "seed_idx": seed_idx,
            })
            temp_prog = Program(code=seed_code, metadata={
                "execution_time": s_output.get("wall_time", 60.0),
                "primary_score": s_score,
            })
            behavior = extractor.extract(temp_prog)
            all_behavior_vectors.append(np.array([behavior[f] for f in extractor.features]))

            # Build prompts for this seed's variants
            seed_prog = Program(code=seed_code, metadata={"score": s_score})
            seed_eval_result = EvaluationResult(
                program_id=seed_prog.id,
                scores={'score': s_score},
                is_valid=True,
            )

            prompts = []
            for _ in range(n_solutions_per_seed):
                builder = PromptBuilder()
                builder.add_section("Problem", PROBLEM_DESCRIPTION, priority=10)
                builder.add_section("Signature", f"```python\n{FUNCTION_SIGNATURE}\n```", priority=20)
                builder.add_parents([ProgramWithScore(seed_prog, seed_eval_result)], priority=30)
                builder.set_output_mode(OutputMode.FULL)
                prompts.append(builder.build())

            # Generate variants in parallel using light models
            llm_tasks = [
                generate_for_island(
                    seed_idx * n_solutions_per_seed + i,
                    prompts[i],
                    LIGHT_MODELS[i % len(LIGHT_MODELS)],
                    0.8
                )
                for i in range(n_solutions_per_seed)
            ]
            results = await asyncio.gather(*llm_tasks)

            # Collect valid candidates
            candidates = []
            for res in results:
                if "error" in res:
                    continue
                total_cost += res["cost"]
                new_code, validation_error = extract_and_validate_code(res["content"])
                if new_code:
                    candidates.append({
                        "code": new_code,
                        "tokens": res.get("tokens", 0),
                        "model": res.get("model", "unknown"),
                    })

            print(f"    {len(candidates)} valid candidates, evaluating...", flush=True)

            # Evaluate candidates
            async def eval_candidate(idx, code):
                try:
                    result = await executor.run(evaluate_code_in_process, code, timeout=60)
                    return idx, result
                except TimeoutError:
                    return idx, {"error": "Timeout"}
                except Exception as e:
                    return idx, {"error": str(e)}

            eval_tasks = [eval_candidate(i, c["code"]) for i, c in enumerate(candidates)]
            eval_outputs = await asyncio.gather(*eval_tasks)
            eval_results = {idx: res for idx, res in eval_outputs}

            # Add evaluated candidates to all_valid_programs
            n_valid = 0
            for i, cand in enumerate(candidates):
                output = eval_results.get(i, {"error": "missing"})
                if "error" in output:
                    continue
                score = score_fn(output)
                execution_time = output.get("wall_time", 60.0)
                all_valid_programs.append({
                    "code": cand["code"],
                    "score": score,
                    "output": output,
                    "execution_time": execution_time,
                    "seed_idx": seed_idx,
                })
                temp_prog = Program(code=cand["code"], metadata={
                    "execution_time": execution_time,
                    "primary_score": score,
                    "workload_1_score": output.get("workload_1_score", 0.0),
                    "workload_2_score": output.get("workload_2_score", 0.0),
                    "workload_3_score": output.get("workload_3_score", 0.0),
                })
                behavior = extractor.extract(temp_prog)
                all_behavior_vectors.append(np.array([behavior[f] for f in extractor.features]))
                n_valid += 1

                if score > global_best_score:
                    global_best_score = score
                    global_best_program = temp_prog

            print(f"    {n_valid} valid programs added (total: {len(all_valid_programs)})", flush=True)

        print(f"\n[Init Phase 3] Total valid programs: {len(all_valid_programs)}", flush=True)

        # Phase 4: Create n_islands islands, each with CVT from random 50% of ALL programs
        print(f"\n[Init Phase 4] Creating {n_islands} islands (CVT from 50% random sample of all programs)...", flush=True)

        islands: list[Island] = []

        for island_idx in range(n_islands):
            # Get the seed for this island
            if island_idx < len(selected_seeds):
                island_seed_code, island_seed_score, _ = selected_seeds[island_idx]
            else:
                # Fallback if we don't have enough seeds
                island_seed_code, island_seed_score, _ = all_seeds[island_idx % len(all_seeds)]

            print(f"\n  [Island {island_idx}] Creating with seed score {island_seed_score:.1f}...", flush=True)

            # Randomly sample 50% of ALL behavior vectors for CVT initialization
            n_sample = max(10, len(all_behavior_vectors) // 2)
            sample_indices = random.sample(range(len(all_behavior_vectors)), min(n_sample, len(all_behavior_vectors)))
            sampled_behaviors = [all_behavior_vectors[i] for i in sample_indices]

            print(f"    Sampling {len(sampled_behaviors)} behaviors (50% of {len(all_behavior_vectors)}) for CVT...", flush=True)

            # Create island with its own CVT pool
            island_extractor = TxnSchedulingBehaviorExtractor(max_time=200.0)
            island_pool = CVTMAPElitesPool(
                behavior_extractor=island_extractor,
                n_centroids=30,  # Smaller per island
                defer_centroids=True,
            )

            # Build centroids from randomly sampled behavior vectors
            if len(sampled_behaviors) >= 3:
                n_centroids = island_pool.set_centroids_from_data(
                    sampled_behaviors,
                    percentile_low=5.0,
                    percentile_high=95.0,
                    n_centroids=30,
                )
            else:
                print(f"    [Island {island_idx}] Not enough behaviors for CVT, using default", flush=True)
                n_centroids = 30

            # Get programs that originated from this island's seed
            island_programs = [p for p in all_valid_programs if p["seed_idx"] == island_idx]
            # Also include the seed itself if not already there
            if not any(p["code"] == island_seed_code for p in island_programs):
                island_programs.insert(0, {
                    "code": island_seed_code,
                    "score": island_seed_score,
                    "output": selected_seeds[island_idx][2] if island_idx < len(selected_seeds) else {},
                    "execution_time": 60.0,
                    "seed_idx": island_idx,
                })

            print(f"    Adding {len(island_programs)} programs from seed {island_idx}...", flush=True)

            # Add programs to island archive
            island_best_score = 0.0
            island_best_program = None
            n_accepted = 0

            for prog in island_programs:
                output = prog.get("output", {})
                child = Program(code=prog["code"], metadata={
                    "execution_time": prog["execution_time"],
                    "primary_score": prog["score"],
                    "workload_1_score": output.get("workload_1_score", 0.0),
                    "workload_2_score": output.get("workload_2_score", 0.0),
                    "workload_3_score": output.get("workload_3_score", 0.0),
                })
                eval_result = EvaluationResult(
                    program_id=child.id,
                    scores={'score': prog["score"]},
                    is_valid=True,
                )
                if island_pool.add(child, eval_result):
                    n_accepted += 1
                    if prog["score"] > island_best_score:
                        island_best_score = prog["score"]
                        island_best_program = child

            island = Island(
                index=island_idx,
                pool=island_pool,
                best_score=island_best_score,
                best_program=island_best_program,
                eval_count=len(island_programs),
                acceptance_count=n_accepted,
            )
            islands.append(island)

            print(f"    [Island {island_idx}] Created with {n_centroids} centroids, {island_pool.size()} elites, best: {island_best_score:.1f}", flush=True)

        print(f"\n[Init] Created {len(islands)} islands, global best: {global_best_score:.1f}, cost: ${total_cost:.3f}", flush=True)

        # Save initial state
        save_multi_island_state(
            generation=0,
            islands=islands,
            global_best_score=global_best_score,
            global_best_program=global_best_program,
            total_cost=total_cost,
            extra_info={"phase": "initialization"},
        )

        return islands

    async def perform_migration(islands: list[Island], eval_count: int):
        """Perform circular migration: island i -> island (i+1) % n."""
        if len(islands) < 2:
            return

        print(f"\n[Migration] Eval #{eval_count}: Performing circular migration (top {migration_fraction*100:.0f}%)...", flush=True)

        n_islands = len(islands)

        # Collect migrants from each island
        all_migrants = []
        for island in islands:
            top_elites = island.get_top_elites(migration_fraction)
            migrants = [(e[0], e[1]) for e in top_elites]  # (Program, EvaluationResult)
            all_migrants.append(migrants)
            print(f"  Island {island.index}: sending {len(migrants)} migrants", flush=True)

        # Circular transfer: island i sends to island (i+1) % n
        total_accepted = 0
        for i in range(n_islands):
            target_idx = (i + 1) % n_islands
            migrants = all_migrants[i]
            accepted = islands[target_idx].receive_migrants(migrants)
            total_accepted += accepted
            print(f"    Island {i} -> Island {target_idx}: {accepted}/{len(migrants)} accepted", flush=True)

        print(f"[Migration] Complete: {total_accepted} total migrants accepted", flush=True)

    async def run_pipeline(islands: list[Island]):
        """
        Multi-island producer-consumer pipeline.

        Similar to single-island but:
        - Candidates are assigned to specific islands
        - Migration occurs every migration_interval evaluations
        """
        nonlocal generation, global_best_score, global_best_program, total_cost

        if not islands:
            print("[Pipeline] No islands to evolve!", flush=True)
            return

        print(f"\n[Pipeline] Starting multi-island evolution with {len(islands)} islands...", flush=True)

        # Configuration
        N_LLM_WORKERS = 4
        N_EVAL_PROCESSES = 4
        EVAL_TIMEOUT = 300
        META_ADVICE_INTERVAL = 50

        # Queues
        sampler_queue = asyncio.Queue()
        eval_queue = asyncio.Queue()
        result_queue = asyncio.Queue()

        pipeline_capacity = asyncio.Semaphore(N_EVAL_PROCESSES + 4)

        # Shared state
        state_lock = asyncio.Lock()
        state = {
            'total_cost': total_cost,
            'eval_count': 0,
            'global_best_score': global_best_score,
            'global_best_program': global_best_program,
            'current_meta_advice': '',
            'previous_meta_advice': '',
            'period_metrics': {
                'total': 0,
                'errors': 0,
                'rejections': 0,
                'acceptances': 0,
                'new_bests': 0,
                'error_messages': set(),
            },
            'llm_in_flight': 0,
            'eval_in_flight': 0,
            'last_migration': 0,
            'migration_count': 0,
        }

        stop_event = asyncio.Event()

        def get_sampler_cycle():
            """Generate sampler configs cycling through islands.

            Samplers per island: softmax, ucb (x2), uniform
            """
            configs = []
            for island in islands:
                # Softmax (1x, heavy model)
                configs.append(("softmax", "softmax", HEAVY_MODEL, island.index))
                # UCB (2x, light models)
                for ucb_idx in range(2):
                    configs.append((f"ucb_{ucb_idx}", "ucb", random.choice(LIGHT_MODELS), island.index))
                # Uniform (1x, light model)
                configs.append(("uniform", "uniform", random.choice(LIGHT_MODELS), island.index))
            random.shuffle(configs)  # Mix islands for fairness
            return configs

        async def sampler_feeder():
            """Feed sampler configs to queue."""
            while not stop_event.is_set():
                configs = get_sampler_cycle()
                for config in configs:
                    if stop_event.is_set():
                        break
                    await sampler_queue.put(config)
                await asyncio.sleep(0.1)

        async def llm_producer(worker_id: int):
            """Generate code for specific island."""
            while not stop_event.is_set():
                slot_acquired = False
                slot_transferred = False
                try:
                    try:
                        display_name, real_sampler, model, island_idx = await asyncio.wait_for(
                            sampler_queue.get(), timeout=2.0
                        )
                    except asyncio.TimeoutError:
                        continue

                    await pipeline_capacity.acquire()
                    slot_acquired = True

                    async with state_lock:
                        if state['total_cost'] >= BUDGET_USD:
                            stop_event.set()
                            break
                        state['llm_in_flight'] += 1
                        current_meta_advice = state['current_meta_advice']

                    # Get island
                    island = islands[island_idx]

                    # Sample from island's pool
                    sample = island.pool.sample(real_sampler, n_parents=1 + n_inspirations)
                    inspirations = [p for p in sample.inspirations if random.random() < 0.8]
                    parents = [sample.parent] + inspirations
                    source_cell = sample.metadata.get("source_cell", 0)

                    # Build prompt
                    builder = PromptBuilder()
                    builder.add_section("Problem", PROBLEM_DESCRIPTION, priority=10)
                    builder.add_section("Signature", f"```python\n{FUNCTION_SIGNATURE}\n```", priority=20)
                    builder.add_parents([ProgramWithScore(p, None) for p in parents], priority=30)
                    builder.set_output_mode(OutputMode.FULL)

                    if current_meta_advice and random.random() < 0.8:
                        builder.add_section("Meta-Advice", current_meta_advice, priority=100)

                    prompt = builder.build()

                    # Generate
                    result = await generate_for_island(worker_id, prompt, model, 0.8)

                    async with state_lock:
                        state['llm_in_flight'] -= 1

                    if "error" in result:
                        print(f"[LLM-{worker_id}] Island {island_idx} {display_name} ERROR: {result['error'][:50]}", flush=True)
                        continue

                    async with state_lock:
                        state['total_cost'] += result["cost"]
                        if state['total_cost'] >= BUDGET_USD:
                            stop_event.set()

                    new_code, validation_error = extract_and_validate_code(result["content"])
                    if not new_code:
                        print(f"[LLM-{worker_id}] Island {island_idx} {display_name} VALIDATION FAIL: {validation_error}", flush=True)
                        continue

                    candidate = {
                        "sampler": display_name,
                        "real_sampler": real_sampler,
                        "code": new_code,
                        "tokens": result.get("tokens", 0),
                        "source_cell": source_cell,
                        "model": model,
                        "island_idx": island_idx,
                    }
                    try:
                        await asyncio.shield(eval_queue.put(candidate))
                        slot_transferred = True
                    except asyncio.CancelledError:
                        slot_transferred = True
                        raise

                except asyncio.CancelledError:
                    async with state_lock:
                        if state['llm_in_flight'] > 0:
                            state['llm_in_flight'] -= 1
                    raise
                except Exception as e:
                    print(f"[LLM-{worker_id}] Unexpected error: {e}", flush=True)
                    async with state_lock:
                        if state['llm_in_flight'] > 0:
                            state['llm_in_flight'] -= 1
                finally:
                    if slot_acquired and not slot_transferred:
                        pipeline_capacity.release()

        async def eval_dispatcher():
            """Dispatch evaluations."""
            pending_evals = set()

            async def run_eval(candidate):
                incremented = False
                output = None
                elapsed = 0
                start = time.time()
                try:
                    async with state_lock:
                        state['eval_in_flight'] += 1
                        incremented = True

                    try:
                        output = await executor.run(evaluate_code_in_process, candidate["code"], timeout=EVAL_TIMEOUT)
                        elapsed = time.time() - start
                    except TimeoutError:
                        output = {"error": f"Timeout after {EVAL_TIMEOUT}s"}
                        elapsed = EVAL_TIMEOUT
                    except asyncio.CancelledError:
                        output = {"error": "Evaluation cancelled"}
                        elapsed = time.time() - start
                        raise
                    except Exception as e:
                        output = {"error": str(e)}
                        elapsed = time.time() - start

                    await result_queue.put({
                        "candidate": candidate,
                        "output": output,
                        "elapsed": elapsed,
                    })
                except asyncio.CancelledError:
                    if output is not None:
                        try:
                            await asyncio.shield(result_queue.put({
                                "candidate": candidate,
                                "output": output,
                                "elapsed": elapsed,
                            }))
                        except Exception:
                            pass
                    raise
                finally:
                    if incremented:
                        async with state_lock:
                            state['eval_in_flight'] -= 1
                    pipeline_capacity.release()

            while not stop_event.is_set() or not eval_queue.empty():
                try:
                    candidate = await asyncio.wait_for(eval_queue.get(), timeout=2.0)
                    task = asyncio.create_task(run_eval(candidate))
                    pending_evals.add(task)
                    task.add_done_callback(pending_evals.discard)
                except asyncio.TimeoutError:
                    continue
                except asyncio.CancelledError:
                    break

            if pending_evals:
                try:
                    await asyncio.wait_for(
                        asyncio.gather(*pending_evals, return_exceptions=True),
                        timeout=EVAL_TIMEOUT + 10
                    )
                except asyncio.TimeoutError:
                    pass

        async def result_processor():
            """Process results, update island archives, trigger migration."""
            nonlocal generation, global_best_score, global_best_program, total_cost

            last_save_time = time.time()

            while not stop_event.is_set() or not result_queue.empty():
                try:
                    try:
                        item = await asyncio.wait_for(result_queue.get(), timeout=1.0)
                    except asyncio.TimeoutError:
                        continue

                    candidate = item["candidate"]
                    output = item["output"]
                    island_idx = candidate["island_idx"]
                    display_name = candidate["sampler"]
                    real_sampler = candidate["real_sampler"]

                    score = score_fn(output)
                    exec_time = output.get("wall_time", 60.0)

                    child = Program(code=candidate["code"], metadata={
                        "execution_time": exec_time,
                        "primary_score": score,
                        "workload_1_score": output.get("workload_1_score", 0.0),
                        "workload_2_score": output.get("workload_2_score", 0.0),
                        "workload_3_score": output.get("workload_3_score", 0.0),
                    })
                    eval_result = EvaluationResult(
                        program_id=child.id,
                        scores={'score': score},
                        is_valid="error" not in output,
                        error=output.get("error"),
                    )

                    async with state_lock:
                        state['eval_count'] += 1
                        state['period_metrics']['total'] += 1
                        eval_count = state['eval_count']
                        current_cost = state['total_cost']

                    island = islands[island_idx]

                    if eval_result.is_valid:
                        accepted = island.pool.add(child, eval_result)
                        island.pool.update_sampler(real_sampler, candidate["source_cell"], success=accepted, reward=score)
                        island.eval_count += 1
                        if accepted:
                            island.acceptance_count += 1
                        makespan = output.get("makespan", BASELINE)

                        async with state_lock:
                            if accepted:
                                state['period_metrics']['acceptances'] += 1
                            else:
                                state['period_metrics']['rejections'] += 1

                            status = "accepted" if accepted else "rejected"
                            if score > island.best_score:
                                island.best_score = score
                                island.best_program = child
                            if score > state['global_best_score']:
                                state['global_best_score'] = score
                                state['global_best_program'] = child
                                global_best_score = score
                                global_best_program = child
                                status = "NEW GLOBAL BEST ★"
                                state['period_metrics']['new_bests'] += 1

                        print(f"[Eval #{eval_count:4d}] I{island_idx} {display_name:15s} {status:18s} | mkspan: {makespan:5.0f} | score: {score:5.1f} | gbest: {global_best_score:5.1f} | ${current_cost:.3f}", flush=True)
                    else:
                        island.pool.update_sampler(real_sampler, candidate["source_cell"], success=False)
                        err = eval_result.error[:30] if eval_result.error else "unknown"

                        async with state_lock:
                            state['period_metrics']['errors'] += 1
                            if eval_result.error:
                                state['period_metrics']['error_messages'].add(eval_result.error[:100].strip())

                        print(f"[Eval #{eval_count:4d}] I{island_idx} {display_name:15s} INVALID            | {err}...", flush=True)

                    # Check for migration (adaptive intervals)
                    async with state_lock:
                        # First migration at migration_intervals[0], then every migration_intervals[1]
                        if state['migration_count'] == 0:
                            next_migration_at = migration_intervals[0]
                        else:
                            next_migration_at = migration_intervals[0] + state['migration_count'] * migration_intervals[1]

                        if eval_count >= next_migration_at:
                            migration_num = state['migration_count'] + 1

                            # Save state BEFORE migration
                            pre_migration_file = STATE_FILE.parent / f"evolution_state_migration_{migration_num}_pre.json"
                            save_multi_island_state(
                                generation=eval_count,
                                islands=islands,
                                global_best_score=state['global_best_score'],
                                global_best_program=state['global_best_program'],
                                total_cost=state['total_cost'],
                                extra_info={"phase": f"pre_migration_{migration_num}"},
                                filename=pre_migration_file,
                            )
                            print(f"[Migration] Saved pre-migration state to {pre_migration_file.name}", flush=True)

                            state['last_migration'] = eval_count
                            state['migration_count'] = migration_num
                            await perform_migration(islands, eval_count)

                            # Save state AFTER migration
                            post_migration_file = STATE_FILE.parent / f"evolution_state_migration_{migration_num}_post.json"
                            save_multi_island_state(
                                generation=eval_count,
                                islands=islands,
                                global_best_score=state['global_best_score'],
                                global_best_program=state['global_best_program'],
                                total_cost=state['total_cost'],
                                extra_info={"phase": f"post_migration_{migration_num}"},
                                filename=post_migration_file,
                            )
                            print(f"[Migration] Saved post-migration state to {post_migration_file.name}", flush=True)

                    # Meta-advice
                    if eval_count > 0 and eval_count % META_ADVICE_INTERVAL == 0:
                        asyncio.create_task(generate_and_update_meta_advice(eval_count))

                    # Save state periodically
                    if time.time() - last_save_time > 30:
                        async with state_lock:
                            save_multi_island_state(
                                generation=eval_count,
                                islands=islands,
                                global_best_score=state['global_best_score'],
                                global_best_program=state['global_best_program'],
                                total_cost=state['total_cost'],
                                extra_info={"phase": "pipeline"},
                            )
                        last_save_time = time.time()

                except asyncio.CancelledError:
                    break
                except Exception as e:
                    print(f"[ResultProc] Unexpected error: {e}", flush=True)

            # Final state update
            async with state_lock:
                total_cost = state['total_cost']
                global_best_score = state['global_best_score']
                global_best_program = state['global_best_program']
                generation = state['eval_count']

        async def generate_and_update_meta_advice(eval_count: int):
            """Generate and update meta-advice."""
            try:
                async with state_lock:
                    metrics_copy = dict(state['period_metrics'])
                    metrics_copy['error_messages'] = set(state['period_metrics']['error_messages'])
                    prev_advice = state['previous_meta_advice']
                    current_cost = state['total_cost']

                progress_pct = (current_cost / BUDGET_USD) * 100
                print(f"\n[Meta-Advice] Generating at eval #{eval_count} ({progress_pct:.0f}% budget)...", flush=True)

                advice, advice_cost = await generate_meta_advice(
                    metrics=metrics_copy,
                    previous_advice=prev_advice,
                    model=HEAVY_MODEL,
                    progress_pct=progress_pct,
                )

                async with state_lock:
                    state['total_cost'] += advice_cost
                    state['previous_meta_advice'] = advice
                    state['current_meta_advice'] = advice
                    state['period_metrics'] = {
                        'total': 0,
                        'errors': 0,
                        'rejections': 0,
                        'acceptances': 0,
                        'new_bests': 0,
                        'error_messages': set(),
                    }

                print(f"[Meta-Advice] Updated (cost: ${advice_cost:.4f})", flush=True)
                print(f"[Meta-Advice]\n{advice}\n", flush=True)
            except Exception as e:
                print(f"[Meta-Advice] Error: {e}", flush=True)

        async def status_monitor():
            """Print periodic status."""
            while not stop_event.is_set():
                await asyncio.sleep(30)
                async with state_lock:
                    island_sizes = [f"I{i.index}:{i.pool.size()}" for i in islands]
                    print(f"\n[Status] Cost: ${state['total_cost']:.3f}/{BUDGET_USD:.2f} | Evals: {state['eval_count']} | "
                          f"LLM: {state['llm_in_flight']} | Eval: {state['eval_in_flight']} | "
                          f"Islands: {' '.join(island_sizes)} | GBest: {state['global_best_score']:.1f}\n", flush=True)

        # Start workers
        print(f"[Pipeline] Starting {N_LLM_WORKERS} LLM workers, {N_EVAL_PROCESSES}-process eval pool...", flush=True)

        feeder_task = asyncio.create_task(sampler_feeder())
        llm_tasks = [asyncio.create_task(llm_producer(i)) for i in range(N_LLM_WORKERS)]
        eval_task = asyncio.create_task(eval_dispatcher())
        processor_task = asyncio.create_task(result_processor())
        monitor_task = asyncio.create_task(status_monitor())

        # Wait for budget exhaustion
        while not stop_event.is_set():
            await asyncio.sleep(1.0)
            async with state_lock:
                if state['total_cost'] >= BUDGET_USD:
                    stop_event.set()

        print(f"\n[Pipeline] Budget exhausted, draining queues...", flush=True)

        # Cleanup
        feeder_task.cancel()
        try:
            await feeder_task
        except asyncio.CancelledError:
            pass

        for task in llm_tasks:
            task.cancel()
        try:
            await asyncio.wait_for(asyncio.gather(*llm_tasks, return_exceptions=True), timeout=10.0)
        except asyncio.TimeoutError:
            pass

        await eval_task

        try:
            await asyncio.wait_for(processor_task, timeout=30.0)
        except asyncio.TimeoutError:
            processor_task.cancel()
            try:
                await processor_task
            except asyncio.CancelledError:
                pass

        monitor_task.cancel()
        try:
            await monitor_task
        except asyncio.CancelledError:
            pass

        # Final save
        save_multi_island_state(
            generation=generation,
            islands=islands,
            global_best_score=global_best_score,
            global_best_program=global_best_program,
            total_cost=total_cost,
            extra_info={"phase": "complete"},
        )

        executor.shutdown()
        print(f"[Pipeline] Complete. Total evals: {generation}", flush=True)

    async def main_async():
        islands = await initialize_islands()
        await run_pipeline(islands)

    asyncio.run(main_async())

    print(f"\n{'='*70}")
    print(f"Multi-Island Evolution Complete")
    print(f"{'='*70}")
    print(f"  Total evaluations:    {generation}")
    print(f"  Global best score:    {global_best_score:.1f}")
    print(f"  Total cost:           ${total_cost:.3f}")
    print(f"{'='*70}\n")

    out = Path(__file__).parent / "best_solution_multi_island.py"
    out.write_text(global_best_program.code)
    print(f"Saved to: {out}")


if __name__ == "__main__":
    main()
