#!/usr/bin/env python3
"""
Ablation Analysis: Generates plots and summary tables.

Reads snapshot.json files from runs/ablations/<ablation>/<condition>_seed<N>/
and produces:
  - Best-so-far curves (mean ± std over seeds)
  - Final archive size bars
  - Summary table (mean±std score, AUC, time-to-threshold, archive size)
  - CSV export

Usage:
  python analyze.py a1                # Archive type ablation
  python analyze.py b1                # Init noise ablation
  python analyze.py d1                # Parallelism ablation
  python analyze.py all               # All ablations
  python analyze.py a1 --vs-time      # Plot vs wall-clock seconds (also generated by default)
"""

import json
import sys
import argparse
import numpy as np
from pathlib import Path

ABLATION_CONDITIONS = {
    "a1": {
        "title": "A1: Archive Type",
        "conditions": ["levi_cvt", "elitist", "uniform_cvt"],
        "labels": {
            "levi_cvt":    "LEVI (CVT, data-driven)",
            "elitist":     "Elitist (1 cell)",
            "uniform_cvt": "Uniform CVT (not data-driven)",
        },
        "x_axis": "eval_number",
        "x_label": "Evaluations",
        "hypothesis": "CVT-MAP-Elites prevents convergence plateau",
    },
    "b1": {
        "title": "B1: Init Noise",
        "conditions": ["no_noise", "low_noise", "high_noise"],
        "labels": {
            "no_noise":   "No noise (σ=0)",
            "low_noise":  "Low noise (σ=0.15)",
            "high_noise": "High noise (σ=0.30)",
        },
        "x_axis": "eval_number",
        "x_label": "Evaluations",
        "hypothesis": "Gaussian init noise reduces early lock-in",
    },
    "d1": {
        "title": "D1: Parallelism",
        "conditions": ["serial", "parallel"],
        "labels": {
            "serial":   "Serial (1 worker)",
            "parallel": "Parallel (8 workers)",
        },
        "x_axis": "timestamp",
        "x_label": "Wall-clock time (s)",
        "hypothesis": "Async engine keeps hardware busy → more progress per dollar",
    },
}

COLORS = ["#2196F3", "#FF5722", "#4CAF50", "#9C27B0", "#FF9800"]


def load_snapshot(run_dir: Path) -> dict | None:
    snap = run_dir / "snapshot.json"
    if not snap.exists():
        return None
    try:
        with open(snap) as f:
            return json.load(f)
    except Exception as e:
        print(f"  Warning: could not load {snap}: {e}")
        return None


def extract_curve(snapshot: dict, x_axis: str = "eval_number") -> list[tuple[float, float]]:
    """Extract (x, best_score) from snapshot score_history."""
    history = snapshot.get("score_history", [])
    curve = []
    for h in history:
        if "best_score" not in h:
            continue
        x = h.get(x_axis, h.get("eval_number", 0))
        curve.append((float(x), float(h["best_score"])))
    return sorted(curve, key=lambda p: p[0])


def compute_auc(curve: list[tuple[float, float]], x_max: float) -> float:
    """AUC of best-so-far curve normalized by x_max."""
    if len(curve) < 2:
        return curve[0][1] if curve else 0.0

    xs = [p[0] for p in curve]
    ys = [p[1] for p in curve]

    # Prepend origin if needed
    if xs[0] > 0:
        xs = [0.0] + xs
        ys = [ys[0]] + ys

    # Clip / extend to x_max
    if xs[-1] < x_max:
        xs.append(x_max)
        ys.append(ys[-1])

    # Clip values beyond x_max
    xs_clip, ys_clip = [], []
    for x, y in zip(xs, ys):
        if x <= x_max:
            xs_clip.append(x)
            ys_clip.append(y)

    if len(xs_clip) < 2:
        return 0.0
    return float(np.trapz(ys_clip, xs_clip)) / x_max


def time_to_threshold(curve: list[tuple[float, float]], pct: float = 0.90) -> float | None:
    """First x where best_score >= pct * final_best."""
    if not curve:
        return None
    final_best = max(y for _, y in curve)
    threshold = pct * final_best
    for x, y in curve:
        if y >= threshold:
            return x
    return None


def load_condition_data(
    ablation_id: str,
    cond_name: str,
    x_axis: str,
    base_dir: Path,
) -> dict:
    """Load all seed data for one condition."""
    cond_dir = base_dir / ablation_id
    data = {
        "curves": [],
        "final_scores": [],
        "aucs": [],
        "ttts": [],          # time-to-threshold (90%)
        "archive_sizes": [],
        "n_evals": [],
        "runtimes": [],
    }

    seed = 0
    while True:
        run_dir = cond_dir / f"{cond_name}_seed{seed}"
        if not run_dir.exists():
            break
        snap = load_snapshot(run_dir)
        if snap:
            curve = extract_curve(snap, x_axis)
            run_state = snap.get("run_state", {})
            arch_size = snap.get("metadata", {}).get("archive_size", 0)
            best_score = run_state.get("best_score", 0.0)
            runtime = run_state.get("elapsed_seconds", 0.0)
            n_evals = run_state.get("eval_count", 0)

            data["curves"].append(curve)
            data["final_scores"].append(best_score)
            data["archive_sizes"].append(arch_size)
            data["runtimes"].append(runtime)
            data["n_evals"].append(n_evals)

            if curve:
                x_max = max(p[0] for p in curve)
                data["aucs"].append(compute_auc(curve, x_max))
                ttt = time_to_threshold(curve)
                if ttt is not None:
                    data["ttts"].append(ttt)

        seed += 1

    return data


def print_summary_table(ablation_id: str, results: dict, meta: dict) -> None:
    """Print a formatted summary table."""
    conditions = meta["conditions"]
    labels = meta["labels"]
    x_label = meta["x_label"]

    print(f"\n{'='*80}")
    print(f"  {meta['title']}")
    print(f"  Hypothesis: {meta['hypothesis']}")
    print(f"{'='*80}")
    header = f"{'Condition':<24} {'Best Score':>14} {'AUC':>10} {'TT90%':>12} {'Archive':>10} {'Evals':>8}"
    print(header)
    print(f"{'-'*80}")

    for cond in conditions:
        r = results[cond]
        label = labels.get(cond, cond)
        if not r["final_scores"]:
            print(f"  {label:<22} {'NO DATA':>60}")
            continue

        mean_s = np.mean(r["final_scores"])
        std_s = np.std(r["final_scores"])
        mean_auc = np.mean(r["aucs"]) if r["aucs"] else float("nan")
        mean_ttt = np.mean(r["ttts"]) if r["ttts"] else float("nan")
        mean_arch = np.mean(r["archive_sizes"])
        mean_evals = np.mean(r["n_evals"])

        print(
            f"  {label:<22} "
            f"{mean_s:>7.2f}±{std_s:<5.2f} "
            f"{mean_auc:>10.2f} "
            f"{mean_ttt:>12.1f} "
            f"{mean_arch:>10.1f} "
            f"{mean_evals:>8.0f}"
        )

    print(f"\n  TT90% units: {x_label}")
    print(f"  AUC: area under best-so-far curve, normalized by x_max")


def save_csv(ablation_id: str, results: dict, meta: dict, base_dir: Path) -> None:
    """Save per-seed results as CSV."""
    rows = ["ablation,condition,seed,best_score,auc,ttt90,archive_size,n_evals,runtime_s"]
    for cond in meta["conditions"]:
        r = results[cond]
        n_seeds = len(r["final_scores"])
        for i in range(n_seeds):
            score = r["final_scores"][i] if i < len(r["final_scores"]) else ""
            auc = r["aucs"][i] if i < len(r["aucs"]) else ""
            ttt = r["ttts"][i] if i < len(r["ttts"]) else ""
            arch = r["archive_sizes"][i] if i < len(r["archive_sizes"]) else ""
            ne = r["n_evals"][i] if i < len(r["n_evals"]) else ""
            rt = r["runtimes"][i] if i < len(r["runtimes"]) else ""
            rows.append(f"{ablation_id},{cond},{i},{score},{auc},{ttt},{arch},{ne},{rt}")

    csv_path = base_dir / ablation_id / f"results_{ablation_id}.csv"
    csv_path.write_text("\n".join(rows))
    print(f"  CSV: {csv_path}")


def plot_ablation(
    ablation_id: str,
    results: dict,
    meta: dict,
    base_dir: Path,
    vs_time: bool = False,
) -> None:
    """Generate plots for one ablation."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("  matplotlib not available, skipping plots")
        return

    conditions = meta["conditions"]
    labels = meta["labels"]
    x_axis = "timestamp" if vs_time else meta["x_axis"]
    x_label = "Wall-clock time (s)" if vs_time else meta["x_label"]

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    fig.suptitle(f"{meta['title']}\n{meta['hypothesis']}", fontsize=12)

    # --- Panel 1: Best-so-far curves ---
    ax = axes[0]
    all_x_maxes = []
    for cond in conditions:
        for curve in results[cond]["curves"]:
            if curve:
                all_x_maxes.append(max(p[0] for p in curve))
    x_max = max(all_x_maxes) if all_x_maxes else 200.0
    x_points = np.linspace(0, x_max, 200)

    for i, cond in enumerate(conditions):
        r = results[cond]
        curves = r["curves"]
        if not curves:
            continue
        label = labels.get(cond, cond)
        color = COLORS[i % len(COLORS)]

        interp_scores = []
        for curve in curves:
            if len(curve) < 2:
                continue
            xs = np.array([p[0] for p in curve])
            ys = np.array([p[1] for p in curve])
            interp = np.interp(x_points, xs, ys)
            interp_scores.append(interp)

        if interp_scores:
            arr = np.array(interp_scores)
            mean = arr.mean(axis=0)
            std = arr.std(axis=0)
            ax.plot(x_points, mean, label=label, color=color, linewidth=2)
            ax.fill_between(x_points, mean - std, mean + std, alpha=0.15, color=color)

    ax.set_xlabel(x_label)
    ax.set_ylabel("Best Score")
    ax.set_title("Best-so-far curve")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # --- Panel 2: Final score distribution ---
    ax2 = axes[1]
    for i, cond in enumerate(conditions):
        r = results[cond]
        if not r["final_scores"]:
            continue
        label = labels.get(cond, cond)
        color = COLORS[i % len(COLORS)]
        scores = r["final_scores"]
        x_pos = i
        ax2.boxplot(scores, positions=[x_pos], widths=0.5,
                    patch_artist=True,
                    boxprops=dict(facecolor=color, alpha=0.6),
                    medianprops=dict(color="black", linewidth=2))

    ax2.set_xticks(range(len(conditions)))
    ax2.set_xticklabels([labels.get(c, c) for c in conditions], rotation=12, ha="right", fontsize=8)
    ax2.set_ylabel("Final Best Score")
    ax2.set_title("Score distribution (seeds)")
    ax2.grid(True, alpha=0.3, axis='y')

    # --- Panel 3: Archive diversity (final size) ---
    ax3 = axes[2]
    bar_vals = []
    bar_errs = []
    bar_labels = []
    for cond in conditions:
        r = results[cond]
        if r["archive_sizes"]:
            bar_vals.append(np.mean(r["archive_sizes"]))
            bar_errs.append(np.std(r["archive_sizes"]))
        else:
            bar_vals.append(0)
            bar_errs.append(0)
        bar_labels.append(labels.get(cond, cond))

    bars = ax3.bar(
        range(len(conditions)), bar_vals,
        yerr=bar_errs,
        color=[COLORS[i % len(COLORS)] for i in range(len(conditions))],
        alpha=0.75, capsize=6
    )
    ax3.set_xticks(range(len(conditions)))
    ax3.set_xticklabels(bar_labels, rotation=12, ha="right", fontsize=8)
    ax3.set_ylabel("Final Archive Size (# occupied cells)")
    ax3.set_title("Archive diversity")
    ax3.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    out_path = base_dir / ablation_id / f"plot_{ablation_id}{'_time' if vs_time else ''}.png"
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    print(f"  Plot: {out_path}")
    plt.close()


def analyze(ablation_id: str, base_dir: Path, vs_time: bool = False) -> None:
    meta = ABLATION_CONDITIONS[ablation_id]
    x_axis = "timestamp" if vs_time else meta["x_axis"]

    print(f"\nAnalyzing ablation: {ablation_id}")

    results = {}
    for cond in meta["conditions"]:
        results[cond] = load_condition_data(ablation_id, cond, x_axis, base_dir)
        n = len(results[cond]["final_scores"])
        print(f"  {cond}: {n} seed(s) loaded")

    print_summary_table(ablation_id, results, meta)
    plot_ablation(ablation_id, results, meta, base_dir, vs_time=vs_time)
    save_csv(ablation_id, results, meta, base_dir)

    # Also generate time-axis plot for d1
    if ablation_id == "d1" and not vs_time:
        print("\n  (also generating vs-eval plot for d1...)")
        x_axis_eval = "eval_number"
        results_eval = {}
        for cond in meta["conditions"]:
            results_eval[cond] = load_condition_data(ablation_id, cond, x_axis_eval, base_dir)
        plot_ablation(ablation_id, results_eval, meta, base_dir, vs_time=False)


def analyze_combined(problems: list[str] | None = None, base_dir: Path = Path("runs/ablations/combined")):
    """Analyze the combined archive×init ablation across problems."""
    conditions = list({
        "levi_full":     "LEVI full (CVT+noise)",
        "no_cvt":        "No archive (elitist)",
        "uniform_init":  "Uniform CVT",
        "no_noise":      "CVT, no init noise",
    }.keys())
    labels = {
        "levi_full":     "LEVI full (CVT+noise)",
        "no_cvt":        "No archive (elitist)",
        "uniform_init":  "Uniform CVT",
        "no_noise":      "CVT, no init noise",
    }
    all_problems = problems or [d.name for d in base_dir.iterdir() if d.is_dir()]

    for problem in all_problems:
        prob_dir = base_dir / problem
        if not prob_dir.exists():
            print(f"No data for problem '{problem}' at {prob_dir}")
            continue

        meta = {
            "title": f"Combined Ablation — {problem}",
            "conditions": conditions,
            "labels": labels,
            "x_axis": "eval_number",
            "x_label": "Evaluations",
            "hypothesis": "CVT archive + data-driven init prevent convergence plateau",
        }

        results = {}
        for cond in conditions:
            results[cond] = load_condition_data(problem, cond, "eval_number", base_dir)
            n = len(results[cond]["final_scores"])
            print(f"  {problem}/{cond}: {n} seed(s) loaded")

        print_summary_table(problem, results, meta)
        plot_ablation(problem, results, meta, base_dir)
        save_csv(problem, results, meta, base_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze ablation results")
    parser.add_argument(
        "ablation", nargs="?", default="all",
        choices=list(ABLATION_CONDITIONS.keys()) + ["all", "combined"],
        help="Which ablation to analyze (default: all)"
    )
    parser.add_argument(
        "--base-dir", default="runs/ablations",
        help="Base directory for ablation runs (default: runs/ablations)"
    )
    parser.add_argument(
        "--vs-time", action="store_true",
        help="Plot vs wall-clock seconds instead of eval count"
    )
    parser.add_argument(
        "--problem", help="For 'combined': restrict to this problem (txn, llm_sql)"
    )
    args = parser.parse_args()

    base_dir = Path(args.base_dir)

    if args.ablation == "combined":
        combined_dir = base_dir / "combined"
        problems = [args.problem] if args.problem else None
        analyze_combined(problems, combined_dir)
    elif args.ablation == "all":
        for aid in ABLATION_CONDITIONS:
            if (base_dir / aid).exists():
                analyze(aid, base_dir, vs_time=args.vs_time)
            else:
                print(f"Skipping {aid} (no data at {base_dir / aid})")
        if (base_dir / "combined").exists():
            analyze_combined(base_dir=base_dir / "combined")
    else:
        analyze(args.ablation, base_dir, vs_time=args.vs_time)
